CREATE TABLE job_applications (
    ID BIGINT IDENTITY,
    EMAIL VARCHAR(254) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(255) NOT NULL,
    CV CLOB NOT NULL,
    MOTIVATION_LETTER CLOB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PIN VARCHAR(8) NOT NULL
)